---
title: "Relapse_outcome"
author: "Chenyi Chen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lubridate)
library(tidyverse)
database <- read.csv("database.csv")
database[database == ""] <- NA
demogs <- database %>% 
  select(id_participant, dob, date_msdx) %>% 
  drop_na(dob)
demogs$dob <- ymd(demogs$dob)
bmi_relapse_df <- read.csv("bmi_relapse_prts.csv") #this is reading in the outpiut from relapse_query_es.rmd
bmi_relapse_df$outcome_date_start <- ymd(bmi_relapse_df$outcome_date_start)
bmi_relapse_df$relapse_date <- ymd(bmi_relapse_df$relapse_date) #formatting dates
bmi_relapse_df
bmi_bcell_relapses <- merge(bmi_relapse_df, demogs, by = "id_participant", all.x = TRUE)
bmi_bcell_relapses
```

```{r}
library(lubridate)
#bmi_bcell_relapses2 <- read.csv("bmi_bcell_relapses.csv")
bmi_bcell_relapses <- bmi_bcell_relapses %>% select(-X)
Combined_data <- bmi_bcell_relapses %>% 
  mutate(time_int = interval(dob, Sys.Date())) %>% 
  mutate(age_mo = time_length(time_int, "month")) %>% 
  mutate(age.x = age_mo/12) %>% 
  select(-time_int, -age_mo) #adding age
Combined_data <- Combined_data %>% dplyr::rename(sample_date = outcome_date_start)
Combined_data
```


## below is code from Wen/Chenyi to generate the relapse outcomes desired (N, annualized relapse rate, and time to first relapse)

# find out outcome wanted: 
```{r}

# Combined_data includes relapse information, clinical information 

# combine all necessary information (relapse history, relapse_date, age, diagnosis date and  sex etc.)
 select_outcome = 
   
   Combined_data  %>% 
   
   
   mutate(date_msdx = as.Date(date_msdx ,format =  "%m/%d/%Y")) %>% 
   mutate(relapse_date =as.Date(ifelse(is.na(relapse_date),date_msdx,relapse_date)))


# day since last relapse (gap between date of first relapse and last relapse) --------------------

select_outcome_gap = select_outcome %>%
  filter(sample_date< relapse_date) %>%  # here we try to look at the data after the outcome start date
  mutate(relapse_time_gap = as.numeric(difftime(sample_date, relapse_date, unit="days")), age = age.x) %>% #find out the time between sample collection and relapse
  
  group_by(id_participant,sample_date) %>%  
  slice(which.min(relapse_time_gap)) # select the closest date of relapse 
select_outcome_gap$relapse_time_gap <- abs(select_outcome_gap$relapse_time_gap)

```

```{r}
# annualized relapse outcome --------------------------------

#ES CHANGE: Made this 3 years instead of 2
## follow up to 3 years then divided by 3 . . . changed back to 2
select_outcome_an1 = 
  select_outcome  %>% 
  mutate(next_2yrs = as.Date(sample_date) + as.difftime(730, unit="days")) %>%
  filter(relapse_date<=next_2yrs & relapse_date> sample_date) %>% 
  dplyr::count(id_participant) %>% 
  mutate(annualized_relapse = n/2)

select_outcome_an = Combined_data %>%  left_join (dplyr::select(select_outcome_an1,id_participant,annualized_relapse)) %>% mutate(annualized_relapse = ifelse(is.na(annualized_relapse), 0, annualized_relapse))  %>%
  group_by(id_participant,sample_date) %>% arrange(id_participant) %>% 
  slice(1)
```


```{r}
# number relapse in last 365 days ---------------------
#ES Edit: I'm making this within the 2 years following first infusion
select_outcome_lastYr1 = 
  select_outcome  %>% 
  mutate(next_yr = as.Date(sample_date) + as.difftime(730, unit="days")) %>%
  filter(relapse_date<= next_yr & relapse_date> sample_date) %>% 
  dplyr::count(id_participant)

select_outcome_lastYr = Combined_data %>%  left_join (dplyr::select(select_outcome_lastYr1,id_participant,n)) %>% mutate(n = ifelse(is.na(n), 0, n))
```


```{r}
# combine 3 main outcome want to use
Combine_df_3outcome =Combined_data %>%  left_join(dplyr::select (select_outcome_gap, c("id_participant","relapse_time_gap") ))  %>%    
  left_join(dplyr::select(select_outcome_an,c("id_participant","annualized_relapse"))) %>% 
  left_join(dplyr::select(select_outcome_lastYr,c("id_participant","n")))   %>% 
  group_by(id_participant,sample_date) %>% arrange(id_participant) %>% 
  slice(1)
```
#THE OUTPUT of this will be used back in BMI B-cell relapse.rmd just before merging with all_repop
```{r}
write.csv(Combine_df_3outcome, "bmi_bcell_relapse_outcomes.csv")
```













